/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cognito_identity_pool_id": "us-west-1:e433c992-e563-4805-bc7f-6399cae5bdd6",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_PbsnTApaq",
    "aws_user_pools_web_client_id": "304anfvvkobj22dlmrfmc3nu0l",
    "oauth": {
        "domain": "sqltrans3564d9a0-3564d9a0-dev.auth.us-west-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/home/sql-generate/,https://sql-translator-1xt8.vercel.app/home/sql-generate/",
        "redirectSignOut": "http://localhost:3000/,https://sql-translator-1xt8.vercel.app/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
